In [ ]:
"""
Create arrays with:
•	int32 
•	float64 
•	bool 
•	datetime64 

"""

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=np.int32)
b = np.array([1.5, 2.3, 3.7, 4.1], dtype=np.float64)
c = np.array([True, False, True, False], dtype=bool)
d = np.array(['2024-01-01', '2024-05-10', '2025-12-25'], dtype='datetime64')

print(a,a.dtype)
print(b,b.dtype)
print(c,c.dtype)
print(d,d.dtype)

[1 2 3 4 5] int32
[1.5 2.3 3.7 4.1] float64
[ True False  True False] bool
['2024-01-01' '2024-05-10' '2025-12-25'] datetime64[D]


In [3]:
"""
Convert:
[1, 2, 3, 4]
to float64
"""

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='float64')

print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float64


In [ ]:
import numpy as np

arr = np.array([1.5, 2.5, 3.5])

print(arr.dtype)