In [1]:
print("Hello")

Hello


In [8]:
import numpy as np

arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
x=np.array(34)
print(x)

34


In [5]:
#2D Array
arr =np.array([
    [10,20,30],[40,50,60]
])
print(arr)

[[10 20 30]
 [40 50 60]]


In [6]:
arr=np.array([1,2,3,4], ndmin=3)
print(arr)
print('number of dimension',arr.ndim)

[[[1 2 3 4]]]
number of dimension 3


In [20]:
arr=np.array=([1,2,3,4,5,6,7])
x=arr[1:6]
print("The value of variable x is",x)

#print(arr[1:5])
#negative slicing----Use the minus operator to refer to a index from the end:

The value of variable x is [2, 3, 4, 5, 6]


In [ ]:
arr = np.array=([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2, 4]


In [4]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array(["Sandesh","Nitesh","Indresh"])

print(a.dtype)
print(b.dtype)

int64
<U7


In [11]:
a=np.array([1,2,3,4],dtype='O')
b=np.array(["Sandesh","Indresh","Nitesh","Saurav"])
print(a.dtype)
#print(b.dtype)

object


In [2]:
import numpy as np
a = np.array([1,2,3,4], dtype='i2')
b = np.array(["Sandesh","Nitesh","Indresh",2,3])

print(a.dtype)
print(b.dtype)

int16
<U21
