In [2]:
import numpy as np
arr = np.array([[1,2,3,4],[6,7,8,9]])
print(f"the dimension this array is (arr.ndim)")
print(arr.shape)

the dimension this array is (arr.ndim)
(2, 4)


In [5]:
arr =np.array ([1,2,3],ndmin=3)
print(arr)
print(f"the dimenion of this array is {arr.ndim}.")

[[[1 2 3]]]
the dimenion of this array is 3.


In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
newarr = arr.reshape(5,2)
print(newarr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [7]:
arr = [1,2,3,4]
result =[]
print(result)

[]


In [8]:
# with vectorization

arr = np.array([1,2,3,4])
result = arr * 2
print(result)

[2 4 6 8]


In [9]:
# without vectorization(loop)
arr = [1,2,3,4]
result = []
for x in arr:
    result.append(x*2)
print(result)

[2, 4, 6, 8]


In [10]:
# arithmetic

arr = np.array([1,2,3])

print(arr + 5)   # [6 7 8]
print(arr * 2)   # [2 4 6]
print(arr - 3)   # [-2 -1  0]

print("Original array:", arr)  # [1 2 3]

[6 7 8]
[2 4 6]
[-2 -1  0]
Original array: [1 2 3]


In [11]:
arr= np.array([10,20,30,40])
arr[arr>25]

array([30, 40])

In [16]:
#write a program to calculate add sub mul div and sqr of an array in numpy also filter the data 
#of each variable taking its value show data greater than mean value

arr = np.array([1,2,3,4,5])
result = arr + 2
print(result)
result = arr - 3
print(result)
result = arr * 5
print(result)
result = arr / 2
print(result)
result = arr ** 1
print(result)

print("Mean result ")

mean_val = np.mean(arr)
print(mean_val)

print("Filter result")
filtered = arr[arr > mean_val]
print(filtered)

[3 4 5 6 7]
[-2 -1  0  1  2]
[ 5 10 15 20 25]
[0.5 1.  1.5 2.  2.5]
[1 2 3 4 5]
Mean result 
3.0
Filter result
[4 5]


In [ ]:
#Mathmetical Function
np.sqrt(arr)
np.log(arr)
np.sin(arr)
np.tan(arr)
np.sum(arr)


np.int64(15)

In [23]:
cost =np.array([100,200,300])
np.sin(cost)
np.cos(cost)
np.tan(cost)
np.log(cost)

array([4.60517019, 5.29831737, 5.70378247])

In [24]:
arr=np.array([1,2,3])

result = arr+10
print(result)

[11 12 13]


In [25]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])

print(a+b)

[[11 22 33]
 [14 25 36]]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([1,2,3])

c= a+b
print(c)

In [ ]:
arr =np.array ([2,4,6,7,8,6,4])
np.sum(arr)
np.mean(arr)
np.min(arr)
np.std(arr)

np.float64(1.9148542155126762)

In [ ]:
#Find mean ,median, mode ,standard deviation, variance min

In [ ]:
a = np.array ([[1,2,3],[2,3,4]])
np.sum(a,axis=0) #column wise sum
np.sum(a,axis=1) #row wise sum 

array([6, 9])

In [30]:
a= np.array([1,2,3,4,5])

print(f"The mean is {np.mean(a)}")
print(f"The median is {np.median(a)}")
print(f"The standard is {np.std(a)}")
print(f"The  variance is {np.var(a)}")
print(f"The min is {np.min(a)}")
print(f"The max is {np.max(a)}")

The mean is 3.0
The median is 3.0
The standard is 1.4142135623730951
The  variance is 2.0
The min is 1
The max is 5


In [33]:
import numpy as np

arr = np.array([2,4,6,7,8,6,4])
brr = np.array([34,56,57,67,89,45,23])

print(np.percentile(arr,10))
print(np.quantile(arr,0.5))
print(np.corrcoef(arr,brr))  # correlation

3.2
6.0
[[1.         0.80349048]
 [0.80349048 1.        ]]
