In [12]:
import numpy as np
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [13]:
import numpy as np
a1 = np.array([1,2,3])
print(a1.ndim)

1


In [18]:
a2=np.array([
    [1,2,3],
    [4,5,6]
])
print(a2.ndim)

2


In [27]:
a3=np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])
print(a3)
print(a3.ndim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2


In [24]:
b=np.zeros((2,3))
print(b)
print(b.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
2


In [30]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [33]:
d=np.arange(0,10,2)
print(d)

[0 2 4 6 8]


In [36]:
d=np.arange(0,12,2)
print(d)

[ 0  2  4  6  8 10]


In [38]:
e=np.linspace(0,1,5)
print(e)

[0.   0.25 0.5  0.75 1.  ]


In [39]:
#given:
 #import numpy as np
#a=np.array([5,10,15,20,25,30])

#Task:
#print the first element
#print the last element
#print the element at index 3



In [40]:
import numpy as np
a=np.array([5,10,15,20,25,30])
print("first element",a[0])
print("last element",a[-1])
print("element at index 3",a[3])

first element 5
last element 30
element at index 3 20


In [46]:
import numpy as np
a=np.array([100,200,300,400,500])
print(a[-1])
print(a[-2])
print(a[-5])

500
400
100


In [ ]:
"""
print the first element and last element and the index at index 3

"""
import numpy as np
b=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
print(b[1,1])
print(b[2,2])
print(b[0,1])


5
9
2


In [50]:
import numpy as np
b=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
#print second row
print(b[1])
#print the first coloum
print(b[:,0])
#print the third row
print(b[2])


[4 5 6]
[1 4 7]
[7 8 9]


In [53]:
import numpy as np

b = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

# 1. Extract:
# [[30,40
#  [70,80]]

# [[20,30]    
#  [60,70]]

print(b[0:2, 1:3])

# 2. Extract last column only
print(b[:, -1])

# 3. Extract sub-matrix:
# [[60,70,80]
#  [100,110,120]]
print(b[1:, 1:])

 #Extract:
# [[30,40
#  [70,80]]
print(b[0:2, 2:4])



[[20 30]
 [60 70]]
[ 40  80 120]
[[ 60  70  80]
 [100 110 120]]
[[30 40]
 [70 80]]


In [5]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a+10)
print(a*2)

#reverse array
print(a[::-1])

[5 7 9]
[11 12 13]
[2 4 6]
[3 2 1]


In [6]:
import numpy as np
c = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
#access element:
print(c[0,1,1])

4


In [7]:

c= np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
#access element:
print(c[0,0,0])
print(c.ndim)

1
3


In [8]:
c= np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
#access element:
print(c[1,0,1])


6


In [9]:
import numpy as np

c = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

# access element:
print(c[1, 1, 0])

7
